"""Curated, clearly labeled learning topics used by Porta's prototype matcher."""

LEARNING_PATHS = [
    {
        "id": "arabic",
        "title": "Everyday Arabic",
        "category": "Languages",
        "description": "Build confidence with useful phrases, pronunciation, and conversation.",
        "keywords": "Arabic language speaking conversation vocabulary dialect Qatar beginner phrases",
        "icon": "Aa",
        "color": "sage",
    },
    {
        "id": "english",
        "title": "English conversation",
        "category": "Languages",
        "description": "Practice speaking clearly for university, work, or daily life.",
        "keywords": "English language IELTS speaking writing pronunciation fluency conversation",
        "icon": "En",
        "color": "peach",
    },
    {
        "id": "coding",
        "title": "Coding & web",
        "category": "Technology",
        "description": "Try Python or JavaScript and turn a small idea into a working project.",
        "keywords": "coding programming Python JavaScript web development technology software beginner",
        "icon": "</>",
        "color": "blue",
    },
    {
        "id": "ai",
        "title": "AI, made practical",
        "category": "Technology",
        "description": "Explore AI tools, prompt design, and how to check AI-generated answers.",
        "keywords": "artificial intelligence AI machine learning prompting generative models data technology",
        "icon": "✳",
        "color": "lilac",
    },
    {
        "id": "university",
        "title": "University study skills",
        "category": "University",
        "description": "Work through challenging topics and build more confident study habits.",
        "keywords": "university college mathematics calculus algebra exam studying science tutoring",
        "icon": "∑",
        "color": "sand",
    },
    {
        "id": "design",
        "title": "Visual & product design",
        "category": "Creative",
        "description": "Get started with Figma, visual communication, and product thinking.",
        "keywords": "creative design graphic visual product Figma drawing portfolio user experience UX",
        "icon": "◈",
        "color": "rose",
    },
    {
        "id": "business",
        "title": "Business & first ideas",
        "category": "Business",
        "description": "Shape a startup idea, practice pitching, or learn the basics of business.",
        "keywords": "business entrepreneurship startup founder marketing finance pitching ideas career",
        "icon": "↗",
        "color": "gold",
    },
]
